const adivice = document.querySelector('.adivice-box')
const id = document.querySelector('h1')
const btn = document.querySelector('button')

const setViewportWidth = () => {
    viewportWidth = window.innerWidth || document.documentElement.clientWidth;
}

const conselhos = [
    "Acredite em si mesmo e siga em frente.",
    "Aproveite cada momento como uma oportunidade única.",
    "Não tenha medo de falhar, pois é através dos erros que aprendemos.",
    "Mantenha uma atitude positiva diante dos desafios.",
    "Seja gentil e generoso com os outros.",
    "Persista e nunca desista dos seus sonhos.",
    "Aprenda com o passado, viva o presente e construa o futuro.",
    "Seja grato pelas pequenas coisas da vida.",
    "Busque o equilíbrio entre o trabalho e o lazer.",
    "Enfrente seus medos e supere-os.",
    "Dedique tempo para cuidar de si mesmo.",
    "Seja resiliente diante das adversidades.",
    "Acredite no seu potencial e nas suas habilidades.",
    "Valorize e cultive seus relacionamentos pessoais.",
    "Aprenda com os erros e siga em frente com sabedoria.",
    "Tenha coragem para tomar as decisões necessárias.",
    "Celebre suas conquistas, por menores que sejam.",
    "Mantenha-se curioso e aberto a novos aprendizados.",
    "Seja paciente e confie no processo.",
    "Aprenda a se perdoar e deixar o passado para trás.",
    "Cultive hábitos saudáveis para o corpo e a mente.",
    "Seja grato pelo que você tem, em vez de focar no que falta.",
    "Não compare sua jornada com a dos outros.",
    "Aproveite as oportunidades de crescimento pessoal e profissional.",
    "Confie na sua intuição e siga seu coração.",
    "Encontre o equilíbrio entre trabalho, lazer e descanso.",
    "Mantenha-se positivo mesmo diante dos desafios.",
    "Aprenda a lidar com a incerteza e a adapte-se às mudanças.",
    "Não tenha medo de pedir ajuda quando necessário.",
    "Acredite que você é capaz de superar qualquer obstáculo.",
    "Cultive a gratidão diária pela vida e pelas pessoas ao seu redor.",
    "Aprenda a ouvir ativamente e se comunicar de forma clara.",
    "Aceite e ame a si mesmo incondicionalmente.",
    "Encontre tempo para cuidar do seu bem-estar mental e emocional.",
    "Mantenha-se focado nos seus objetivos e não desvie do seu caminho.",
    "Desenvolva resiliência para lidar com os altos e baixos da vida.",
    "Seja gentil consigo mesmo e com os outros.",
    "Cultive relacionamentos saudáveis e genuínos.",
    "Aprenda com as críticas construtivas e deixe de lado as negativas.",
    "Permita-se explorar sua criatividade e expressar-se livremente.",
    "Valorize o poder do agora e viva o momento presente.",
    "Celebre suas realizações e os progressos que você conquista.",
    "Seja autêntico e verdadeiro consigo mesmo.",
    "Aprenda a definir limites saudáveis em seus relacionamentos.",
    "Cultive o hábito da leitura e do aprendizado contínuo.",
    "Mantenha-se humilde e disposto a aprender com os outros.",
    "Aceite que o fracasso faz parte do caminho para o sucesso.",
    "Pratique a empatia e tente compreender o ponto de vista dos outros.",
    "Encontre tempo para relaxar e recarregar suas energias.",
    "Aprenda a lidar com o estresse e o autocuidado é essencial.",
    "Busque a felicidade nas coisas simples do dia a dia.",
    "Seja grato pelo que você tem antes de buscar mais.",
    "Acredite que você merece alcançar seus sonhos e objetivos.",
    "Cultive a paciência e saiba que tudo tem o seu tempo certo.",
    "Aprenda a se perdoar e permita-se recomeçar quantas vezes for necessário.",
    "Valorize os momentos de conexão e amor com as pessoas queridas.",
    "Seja proativo e tome a iniciativa para alcançar seus objetivos.",
    "Aprenda a lidar com a rejeição e veja como uma oportunidade de crescimento.",
    "Mantenha uma postura positiva mesmo diante dos desafios.",
    "Cultive a autocompaixão e seja gentil consigo mesmo.",
    "Aceite as mudanças como oportunidades de crescimento pessoal.",
    "Aprenda a administrar seu tempo e priorize o que é mais importante.",
    "Busque o equilíbrio entre o trabalho, o lazer e o descanso.",
    "Mantenha-se aberto a novas experiências e novas perspectivas.",
    "Acredite na sua capacidade de superar obstáculos e adversidades.",
    "Cultive a honestidade e a integridade em todas as suas ações.",
    "Aprenda a ouvir sua intuição e confie em sua sabedoria interior.",
    "Valorize cada pequena conquista ao longo do caminho.",
    "Seja grato pelos desafios, pois eles trazem oportunidades de crescimento.",
    "Aprenda a delegar tarefas e confie nas habilidades dos outros.",
    "Mantenha uma mentalidade de crescimento e esteja disposto a aprender.",
    "Cultive a resiliência e a capacidade de se adaptar às mudanças.",
    "Aceite que nem tudo está sob seu controle e foque no que você pode influenciar.",
    "Aprenda a dizer não quando necessário e defenda seus limites.",
    "Busque a simplicidade e desapegue-se do excesso.",
    "Mantenha-se presente e atento ao momento presente.",
    "Cultive a compaixão e ajude os outros sempre que puder.",
    "Aprenda a lidar com a crítica construtiva e utilize-a como oportunidade de crescimento.",
    "Valorize suas habilidades e reconheça suas conquistas.",
    "Seja resiliente e persista diante dos desafios.",
    "Aprenda a lidar com a incerteza e mantenha uma mente aberta.",
    "Mantenha uma atitude positiva e otimista diante da vida.",
    "Cultive relacionamentos saudáveis e nutra suas amizades.",
    "Aprenda a aproveitar a solidão e encontrar paz em sua própria companhia.",
    "Aceite-se plenamente e ame a si mesmo incondicionalmente.",
    "Aprenda a se comunicar de forma clara e eficaz.",
    "Mantenha uma mente aberta e esteja disposto a aprender com os outros.",
    "Cultive a humildade e reconheça que sempre há mais a aprender.",
    "Aprenda a perdoar e deixe o passado para trás.",
    "Encontre tempo para praticar atividades que lhe trazem alegria e satisfação.",
    "Acredite na sua capacidade de superar desafios e alcançar seus objetivos.",
    "Seja gentil consigo mesmo e com os outros em todas as situações.",
    "Cultive a gratidão diária pelas pequenas coisas da vida.",
    "Aprenda a lidar com o estresse e busque o equilíbrio em todas as áreas da sua vida.",
    "Mantenha-se focado e persista mesmo diante das dificuldades.",
    "Acredite na sua capacidade de fazer a diferença no mundo.",
    "Cultive a paciência e confie no processo de crescimento pessoal.",
    "Aprenda a ouvir sua intuição e siga seu coração em todas as decisões.",
    "Valorize e cuide da sua saúde física, mental e emocional.",
    "Seja grato pelos relacionamentos significativos em sua vida.",
    "Cultive a resiliência e a capacidade de se adaptar às mudanças.",
    "Aprenda a lidar com a pressão e mantenha-se calmo em situações desafiadoras.",
    "Mantenha uma visão positiva do futuro e acredite nas suas possibilidades.",
    "Aprenda a trabalhar em equipe e valorize a colaboração.",
    "Cultive a autenticidade e seja verdadeiro consigo mesmo e com os outros.",
    "Aceite os erros como oportunidades de aprendizado e crescimento.",
    "Acredite que você tem o poder de criar a vida que deseja.",
    "Mantenha uma atitude de gratidão e aprecie cada momento.",
    "Aprenda a lidar com a rejeição e siga em frente com determinação.",
    "Busque o equilíbrio entre o trabalho e a vida pessoal.",
    "Cultive a criatividade e explore sua expressão artística.",
    "Aprenda a desafiar-se e sair da sua zona de conforto.",
    "Seja responsável pelas suas escolhas e ações.",
    "Cultive a paz interior e encontre momentos de tranquilidade em sua rotina.",
    "Aprenda a perdoar a si mesmo e aos outros.",
    "Valorize suas próprias habilidades e confie no seu potencial.",
    "Mantenha-se fiel aos seus valores e princípios.",
    "Cultive a perseverança e nunca desista dos seus sonhos.",
    "Aprenda a encontrar o lado positivo em todas as situações.",
    "Busque o crescimento pessoal e profissional de forma contínua.",
    "Cultive a curiosidade e mantenha-se aberto a novas experiências.",
    "Aprenda a administrar seu tempo de forma eficaz e priorize suas tarefas.",
    "Seja gentil e respeitoso com todas as pessoas que você encontra.",
    "Acredite na sua capacidade de superar desafios e alcançar o sucesso.",
    "Mantenha uma postura positiva diante dos desafios e obstáculos.",
    "Cultive relacionamentos saudáveis e nutra suas conexões com as pessoas.",
    "Aprenda a lidar com a crítica e utilize-a para crescer e melhorar.",
    "Valorize e cuide do seu bem-estar físico, mental e emocional.",
    "Mantenha-se presente no momento atual e pratique a atenção plena.",
    "Cultive a gratidão e aprecie as coisas simples da vida.",
    "Aprenda a se colocar em primeiro lugar e cuidar de si mesmo.",
    "Aceite as mudanças como oportunidades de crescimento e transformação.",
    "Mantenha uma mentalidade de crescimento e esteja aberto a aprender sempre.",
    "Cultive a empatia e coloque-se no lugar das outras pessoas.",
    "Aprenda a se perdoar e deixe o passado no passado.",
    "Busque o equilíbrio entre o trabalho, a família e o lazer.",
    "Acredite em si mesmo e nas suas capacidades.",
    "Cultive a positividade e mantenha o otimismo mesmo diante dos desafios.",
    "Aprenda a enfrentar seus medos e se tornar mais corajoso.",
    "Valorize os pequenos momentos de felicidade no dia a dia.",
    "Mantenha uma atitude de gratidão e aprecie as coisas boas da vida.",
    "Cultive a autenticidade e seja verdadeiro consigo mesmo e com os outros.",
    "Aprenda a lidar com o estresse e encontre formas saudáveis de relaxar.",
    "Aceite-se como você é e ame-se incondicionalmente.",
    "Mantenha-se motivado e persista mesmo diante dos obstáculos.",
    "Cultive a resiliência e a capacidade de se adaptar às mudanças.",
    "Aprenda a ouvir sua intuição e confie nas suas decisões.",
    "Valorize sua saúde e bem-estar físico, mental e emocional.",
    "Seja grato pelas pessoas e experiências em sua vida.",
    "Cultive a paciência e saiba que tudo acontece no tempo certo.",
    "Aprenda a abraçar a imperfeição e valorizar o progresso.",
    "Mantenha uma atitude positiva e otimista diante dos desafios.",
    "Cultive relacionamentos saudáveis e valorize as pessoas ao seu redor.",
    "Aprenda a se perdoar e deixar o passado para trás.",
    "Aceite as mudanças como oportunidades de crescimento e evolução.",
    "Mantenha uma mente aberta e esteja disposto a aprender sempre.",
    "Cultive a gentileza e espalhe bondade por onde passar.",
    "Aprenda a enfrentar seus medos e sair da sua zona de conforto.",
    "Valorize as pequenas vitórias ao longo do caminho.",
    "Mantenha-se focado nos seus objetivos e não desista diante dos obstáculos.",
    "Cultive a honestidade e seja verdadeiro consigo mesmo e com os outros.",
    "Aprenda a se adaptar às mudanças e encontrar oportunidades em cada situação.",
    "Valorize e cuide do seu bem-estar físico, mental e emocional.",
    "Mantenha uma atitude de gratidão e aprecie as coisas boas da vida.",
    "Cultive relacionamentos significativos e nutra suas conexões com as pessoas.",
    "Aprenda a se perdoar e deixar o passado no passado.",
    "Seja gentil consigo mesmo e pratique a autocompaixão.",
    "Acredite na sua capacidade de superar desafios e alcançar seus objetivos.",
    "Cultive a resiliência e a capacidade de se levantar após quedas.",
    "Aprenda a ouvir sua intuição e siga seu coração em suas decisões.",
    "Valorize e cuide da sua saúde física, mental e emocional.",
    "Mantenha uma mente aberta e esteja disposto a aprender com os outros.",
    "Cultive a positividade e encontre o lado bom em todas as situações.",
    "Aprenda a lidar com o estresse e encontre formas saudáveis de lidar com ele.",
    "Seja grato pelo que você tem e aprecie as pequenas coisas da vida.",
    "Mantenha-se presente no momento atual e aproveite o aqui e agora.",
    "Cultive relacionamentos saudáveis e valorize as pessoas ao seu redor.",
    "Aprenda a se perdoar e deixar o passado para trás.",
    "Aceite as mudanças como oportunidades de crescimento e transformação.",
    "Mantenha uma atitude positiva e otimista mesmo diante dos desafios.",
    "Cultive a empatia e coloque-se no lugar das outras pessoas.",
    "Aprenda a lidar com a crítica construtiva e utilize-a para crescer.",
    "Valorize sua própria jornada e não compare sua vida com a dos outros.",
    "Mantenha-se fiel aos seus valores e princípios.",
    "Cultive a paciência e confie no processo de crescimento pessoal.",
    "Aprenda a ouvir sua intuição e siga o que ressoa com você.",
    "Aceite-se como você é e ame-se incondicionalmente.",
    "Mantenha-se focado em seus objetivos e não desista diante dos obstáculos.",
    "Cultive a resiliência e a capacidade de se recuperar dos desafios.",
    "Aprenda a apreciar as coisas simples e encontre alegria nos pequenos momentos.",
    "Valorize seus relacionamentos e invista tempo em conexões significativas.",
    "Mantenha uma mentalidade aberta e esteja disposto a aprender e crescer.",
    "Cultive a gratidão diária e encontre motivos para agradecer.",
    "Aprenda a se perdoar e liberar qualquer culpa ou arrependimento.",
    "Aceite as mudanças como oportunidades de crescimento e renovação.",
    "Mantenha uma postura positiva e otimista mesmo diante dos desafios.",
    "Cultive a empatia e a compreensão pelas experiências dos outros.",
    "Aprenda a lidar com a crítica e utilize-a como uma oportunidade de melhoria.",
];

btn.addEventListener('click', () => {
    setViewportWidth();
    const conselhoAleatorio = conselhos[Math.floor(Math.random() * conselhos.length)];

    if (viewportWidth < 800) {
        adivice.innerHTML = `
            <p>“${conselhoAleatorio}”</p>
        `;
        id.textContent = `Conselho #${conselhos.indexOf(conselhoAleatorio) + 1}`;
    } else {
        adivice.innerHTML = `
            <p>“${conselhoAleatorio}”</p>
        `;
        id.textContent = `CONSELHO #${conselhos.indexOf(conselhoAleatorio) + 1}`;
    }
});
